spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ceramic_db
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: true

telegram:
  bot:
    useranme: "@cermic_bot"
    token: "7444933783:AAEElUXdI5K0_gADVXzzR3jVy3aH27ydXQc"